app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:https://ai-resumeforge.netlify.app}
ai.gemini.api-key=${GEMINI_API_KEY:}
ai.gemini.model=gemini-2.5-flash
ai.gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models}
ai.openrouter.api-key=${OPENROUTER_API_KEY:}
ai.openrouter.model=openai/gpt-4o-mini
ai.openrouter.url=${OPENROUTER_URL:https://openrouter.ai/api/v1/chat/completions}
ai.local.enabled=${LOCAL_AI_ENABLED:false}
ai.local.url=${LOCAL_AI_URL:http://localhost:11434}
